Simple Edge Walker
Bentleysb/atlas pull request #5
Opened 2018-11-13 18:26 UTC by Bentleysb

### Description:

This adds a simple implementation of the abstract EdgeWalker class. This saves creating a new implementation each time only a basic walker is needed. This walker allows the candidate selection and filtering functions to be passed in at instantiation. This makes it quite adaptable, as long the only output required is a single unsorted set of collected edges. 

### Potential Impact:

No immediate effect, as this is a new class. However, this can be used to replace existing custom walkers in some atlas-checks' checks (e.g InvalidLanesTagCheck, EdgeCrossingEdgeCheck, MalformedRoundaboutCheck)

### Unit Test Approach:

Unit test `collectAllTest` checks the `SimpleEdgeWalker(Edge, Function)` constructor, and checks the infinite loop protection built into the `collectEdges` method.
Unit test `collectPrimaryQueueAllTest` checks the `SimpleEdgeWalker(Edge, Predicate, Function)` constructor. 

### Test Results:

NA

------

In doubt: [Contributing Guidelines](CONTRIBUTING.md)

2018-11-13 21:35 UTC, nachtm reviewed
Implementation looks solid, and I can definitely see this being helpful! I have two overall questions/comments:

- Should this go in atlas or atlas-checks? 
- I'm also wondering about your PR on ShadowDetection, which is also using a BFS. However, that's not searching over edges so we can't use this utility there. It would be super cool to generalize this further, though that's likely something to do down the road.

2018-11-13 21:50 UTC, Bentleysb commented
I think this fits in atlas, as it is just a usability extension to the EdgeWalker class. If the EdgeWalker fits in Atlas, this does. 
I agree it would be great to have a BFS that could be used more generally. This is just a quick way to make an existing class more usable. We should definitely look into what that could look like and where that would live.

2018-11-13 21:52 UTC, nachtm approved these changes
Sounds good! Thanks for doing this :)

2018-11-21 13:14 UTC, danielduhh requested changes
Had a single nit. Thanks for doing this; I wasn't fully convinced this belongs in Atlas, but you made a good point about the EdgeWalker being in the same package.

Also... nice name!

2018-11-21 13:14 UTC, danielduhh commented on src/main/java/org/openstreetmap/atlas/geography/atlas/walker/SimpleEdgeWalker.java
> + * This class provides some constructors for simple {@link EdgeWalker}s.
Could you elaborate a bit more here?

2018-11-21 21:25 UTC, danielduhh approved these changes

2018-11-26 16:41 UTC, closed without merging